# Basic configuration
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'TheStormThatIsApproaching'
theme = 'hugo-bearcub'
copyright = 'TheStormThatIsApproaching (MIT)'
defaultContentLanguage = 'en'
enableRobotsTXT = true

# Syntax highlighting
[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    # This allows Bear Cub to use a variation of Dracula that is more accessible
    # to people with poor eyesight. For more information about color contrast
    # and accessibility, see https://web.dev/color-and-contrast-accessibility/
    noClasses = false

[params]
  description = 'My personal blog and portfolio'
	favicon = 'images/favicon.png'
	images = ['images/socialcard.jpg']
	title = 'My blog'
	generateSocialCard = true
  madeWith = 'Made with [Bear Cub](https://github.com/clente/hugo-bearcub) & [Hugo](https://gohugo.io)'

  [params.author]
	  name = 'pixoul'
		# email = ''
